module.exports = {
	//Please follow same naming convention for files as well as key as its there in this file
	AdminSessionService: require("./adminSessionService"),
	BaseService: require("./base"),
	SessionsService: require("./sessionService"),
	CategoriesService: require("./categoriesService"),
	ServiceService: require("./serviceService"),
	AdminService: require("./adminService"),
	AdminPermissionService: require("./adminPermissionService"),
	IndustriesService: require("./industriesService"),
	JobTitleService: require("./jobTitleService"),
	UniversityService: require("./universityService"),
	EmploymentTypeService: require("./employmentTypeService"),
	SpecializationService: require("./specializationService"),
	SkillsService : require("./skillsService"),
	TravelRequirementsService : require("./travelRequirementService"),
	SecurityClearanceService : require("./securityClearanceService"),
	UserService: require("./userService"),
	UserBuildResumeService: require("./userBuildResumeService"),
	UserDocumentsService: require("./userDocumentsService"),
	AdminUserService: require("./adminUserService"),
	RecruiterService: require("./recruiterService"),
	RecruiterSessionService: require("./recruiterSessionService"),
	AdminRecruiterService: require("./adminRecruiterService"),
	SuggestSkillsService: require("./suggestSkillsService"),
	UserSuggestSkills: require("./userSuggestSkills"),
	PaymentPlanService:require("./paymentPlanService"),
	BenefitsService: require("./benefitsService"),
	ScheduleService: require("./scheduleService"),
	SupplementService: require("./supplementService"),
	EligibleService: require("./eligibleService"),
	PersonalitiesService: require("./personalitiesService"),
	HireService: require("./hireService"),
	AdminScreeningQuestionService: require("./adminScreeningQuestionService"),
	JobPostService:require("./jobPostService"),
	AdminNotificationMessageService: require("./adminNotificationMessageService"),
	AdminNotificationService: require("./adminNotificationService"),
	UserJobService: require("./userJobService"),
	AdminSecurityClearenceService: require("./adminSecurityClearenceService"),
	GroupPermission: require("./GroupPermission"),
	RecruiterUserService: require("./recruiterUserService"),
	FavouriteAndSkippedService:require("./favouriteAndSkippedService"),
	RecruiterSearchService:require("./recruiterSearchService"),
	AdminJobsPostedService: require("./adminJobPostedServices"),
	RecruiterPaymentService: require("./recruiterPaymentService"),
	AdminSuccessStoriesService: require("./adminSuccessStoriesServices"),
	ReportServices: require("./reportServices"),
	ChatService: require("./chatService"),
	AdminPromoCodeServices: require("./adminPromoCodeServices"),
	UserNotificationService:require("./userNotificationService"),
	UserTurnOffNotificationService:require("./userTurnOffNotificationService"),
	RecruiterDashboardService:require("./recruiterDashboardService"),
	RecruiterReportService:require("./recruiterReportService"),
	RecruiterTemplateService: require("./recruiterTemplateServices"),
};